import GLib from 'gi://GLib';

const ZH = {
    'language.label': '语言',
    'window.subtitle': '给鼠标动作配快捷键',
    'action.save': '保存',
    'action.cancel': '取消',
    'action.delete': '删除',
    'action.discard': '丢掉',
    'action.keepEditing': '继续编辑',
    'action.add': '添加',
    'action.done': '完成',
    'action.record': '录制',
    'action.rerecord': '重录',
    'action.ok': '好',
    'dirty.title': '有修改还没保存',
    'dirty.closeTitle': '还有没保存的修改',
    'dirty.closeBody': '关掉窗口会丢掉这些修改。',
    'language.switchTitle': '切换语言',
    'language.switchBody': '还有没保存的修改。要先保存再切换吗？',
    'language.saveSwitch': '保存并切换',
    'language.discardSwitch': '不保存并切换',
    'mouse.group': '鼠标',
    'mouse.many': '这台电脑有多只鼠标。保存后使用下面这一只。',
    'mouse.one': '保存后使用这只鼠标。',
    'mouse.use': '使用这只',
    'mouse.none': '没有找到鼠标',
    'trigger.group': '轨迹',
    'trigger.description': '画轨迹时按住这个键。鼠标组合不看它，以你先按下的那个键为准。',
    'trigger.label': '触发键',
    'display.group': '显示',
    'display.description': '屏幕上的轨迹和成功后的名字。保存后，下一笔就会换上。',
    'display.namePlace': '名字位置',
    'display.bottom': '屏幕下方居中',
    'display.pointer': '松手的地方',
    'display.width': '线条粗细',
    'display.pixels': '像素',
    'recognize.group': '识别',
    'recognize.description': '单位是这只鼠标自己的移动量，不是屏幕像素。保存后，下一笔就换上。',
    'recognize.click': '仍算点击',
    'recognize.clickHint': '移动不超过这个距离，就当普通点击',
    'recognize.length': '最短轨迹',
    'recognize.lengthHint': '短于这个距离不算一笔',
    'recognize.duration': '最长按住',
    'recognize.durationHint': '毫秒。超过就取消这一笔',
    'recognize.maxRules': '最多规则',
    'recognize.rulesUnit': '条',
    'rules.group': '规则',
    'rules.addTooltip': '添加一条规则',
    'rules.emptyHint': '点这一栏右边的「添加」。一条规则是一个鼠标动作，加上要按下的快捷键。',
    'rules.count': '点一条可以修改。已有 {count} 条，最多 {max} 条。',
    'rules.emptyTitle': '还没有规则',
    'rules.emptySubtitle': '添加后，选画轨迹、按两个鼠标键，或按住再滚轮，再录快捷键。',
    'rules.deleteTooltip': '删除这条规则',
    'rules.max': '最多 {max} 条规则',
    'rules.deleteTitle': '删除「{name}」？',
    'rules.deleteBody': '这条规则会从列表里去掉。要点保存才会写进文件。',
    'save.failed': '没有保存',
    'save.mouse': '已保存，已换上这只鼠标',
    'save.reloaded': '已保存，正在运行的演示已换上新规则',
    'save.later': '已保存。下次启动时会用这份规则',
    'shape.wheel': '按住{hold}，滚轮{direction}',
    'shape.chord': '按住{hold}，再按{press}',
    'shape.drawn': '按住{trigger}画的轨迹',
    'shape.direction': '按住{trigger}{direction}',
    'shape.unset': '还没设置动作',
    'kind.wheel': '滚轮',
    'kind.chord': '组合',
    'kind.stroke': '轨迹',
    'direction.up': '向上',
    'direction.down': '向下',
    'direction.left': '向左',
    'direction.right': '向右',
    'button.left': '左键',
    'button.right': '右键',
    'button.middle': '中键',
    'button.forward': '侧键前进',
    'button.back': '侧键后退',
    'rule.untitled': '未完成',
    'rule.noShortcut': '未设置',
    'editor.new': '新规则',
    'editor.edit': '编辑规则',
    'editor.how': '怎么触发',
    'editor.howDescription': '只选一种。画轨迹用窗口里的触发键。鼠标组合和滚轮以你先按下的键为准。',
    'editor.draw': '画出轨迹',
    'editor.drawEmpty': '按住{trigger}，在屏幕上画一笔后松开',
    'editor.chord': '鼠标组合',
    'editor.chordEmpty': '先按住一个键，再按另一个',
    'editor.wheel': '按住再滚轮',
    'editor.wheelEmpty': '先按住一个键，再滚一下滚轮',
    'editor.preview': '轨迹预览',
    'editor.previewReady': '小点是起点，大点是松开的地方。',
    'editor.previewEmpty': '画出之后，轨迹会显示在这里。',
    'editor.then': '然后做什么',
    'editor.thenDescription': '录快捷键时键盘会暂时独占，系统不会先把这组键吃掉。',
    'editor.shortcut': '快捷键',
    'editor.shortcutEmpty': '还没录',
    'editor.screenName': '屏幕上显示',
    'editor.nameGroup': '屏幕提示',
    'editor.nameDescription': '留空则不显示。识别成功后出现大约一秒。位置在「显示」里选。',
    'editor.cancelled': '已取消',
    'editor.noBinary': '找不到 strokelet',
    'editor.drawPrompt': '按住{trigger}画出轨迹，然后松开。',
    'editor.drawSaved': '轨迹已记下。点完成后才会写进这条规则。',
    'editor.notSaved': '这次没有保存',
    'editor.chordPrompt': '先按住起始键，再按另一个。左键、右键、中键或侧键都可以。',
    'editor.chordSaved': '鼠标组合已记下。点完成后才会写进这条规则。',
    'editor.wheelPrompt': '先按住一个鼠标键，再滚一下滚轮。向上、向下或左右都可以。',
    'editor.wheelSaved': '滚轮动作已记下。点完成后才会写进这条规则。',
    'editor.shortcutPrompt': '键盘已暂时独占。按下快捷键，松开主键后记下。',
    'editor.listening': '正在听：{label}',
    'editor.listeningPlain': '正在听…',
    'editor.shortcutSaved': '快捷键已记下。点完成后才会写进这条规则。',
    'editor.needStroke': '先画出轨迹，或改选另一种动作。',
    'editor.needChord': '先按下两个鼠标键，或改选另一种动作。',
    'editor.needWheel': '先按住鼠标键并滚动滚轮，或改选另一种动作。',
    'editor.needShortcut': '再录一组快捷键。',
    'editor.nameTooLong': '屏幕名称最多 16 个字。',
    'editor.noCheck': '找不到 strokelet，无法检查轨迹',
    'editor.invalid': '规则无效',
    'editor.noResult': '录制没有返回结果',
    'editor.interrupted': '录制中断',
    'editor.previewPlaceholder': '画出后显示在这里',
    'menu.disconnected': '未连接',
    'menu.connected': '已连接',
    'menu.settings': '设置',
    'menu.pause': '暂停',
    'menu.resume': '启动',
    'menu.quit': '退出',
    'error.clickRange': '仍算点击的距离要在 1 到 400 之间',
    'error.lengthRange': '最短轨迹要大于仍算点击的距离，并且在 20 到 5000 之间',
    'error.durationRange': '最长按住要在 200 到 60000 毫秒之间',
    'error.ruleCount': '规则条数要在 1 到 64 之间',
    'error.tooManyRules': '最多 {max} 条规则',
    'error.wheelAndButton': '这条规则不能同时有鼠标组合和滚轮',
    'error.strokeAndButton': '这条规则不能同时有轨迹和鼠标组合',
    'error.duplicateWheel': '这个滚轮动作已经有一条规则',
    'error.sameButton': '组合的两个键不能相同',
    'error.duplicateChord': '这个鼠标组合已经有一条规则',
    'error.similarStroke': '这条轨迹和已有的太像',
    'error.nameNewline': '屏幕名称不能换行',
    'error.nameLength': '屏幕名称最多 16 个字',
    'error.bothShapes': 'stroke uses both a direction and points',
    'error.shortStroke': 'stroke needs at least two points',
    'error.longStroke': 'stroke has too many points',
    'error.pointRange': 'stroke point is out of range',
    'error.mixedShortcut': 'shortcut uses both names and key codes',
    'error.emptyKey': 'shortcut key is empty',
    'daemon.noKeyboard': '没有找到键盘',
    'daemon.timeout': '时间到了，这次没有保存',
    'daemon.draw': '按住{button}，在屏幕上画一笔，然后松开。',
    'daemon.wheelHint': '先按住一个鼠标键，再滚一下滚轮。',
    'daemon.chordHint': '先按住起始键，再按另一个。左键、右键、中键或侧键都可以。',
    'daemon.grabbedDraw': '鼠标已暂时独占。按住{button}，画一笔后松开。',
    'daemon.grabbedWheel': '鼠标已暂时独占。先按住一个鼠标键，再滚一下滚轮。',
    'daemon.noWheel': '没有滚到滚轮',
    'daemon.badHold': '这个键不能当作起始键',
    'daemon.grabbedChord': '鼠标已暂时独占。先按住起始键，再按另一个。',
    'daemon.noSecond': '没有按到另一个鼠标键',
    'daemon.badChord': '这个键不能当作组合',
    'daemon.mouseBusy': '鼠标被占用。请先在面板上暂停 Strokelet。',
    'daemon.tooLong': '时间太长，这次没有保存',
    'daemon.tooShort': '轨迹太短',
    'daemon.another': '已开始另一次录制',
    'daemon.released': '演示放开了鼠标，这次没有保存',
    'daemon.notSaved': '这次没有保存',
    'daemon.tooManyModifiers': '修饰键最多 4 个',
    'daemon.badKey': '这个键不能绑定',
    'daemon.cancelled': '已取消',
    'daemon.twoKeys': '按下了两个主键，请再录一次',
    'daemon.drawTimeout': '8 秒内没有画完一笔',
    'daemon.wheelTimeout': '8 秒内没有滚到滚轮',
    'daemon.chordTimeout': '8 秒内没有按到另一个鼠标键',
};

const EN = {
    'language.label': 'Language',
    'window.subtitle': 'Shortcuts for mouse actions',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.delete': 'Delete',
    'action.discard': 'Discard',
    'action.keepEditing': 'Keep editing',
    'action.add': 'Add',
    'action.done': 'Done',
    'action.record': 'Record',
    'action.rerecord': 'Record again',
    'action.ok': 'OK',
    'dirty.title': 'Unsaved changes',
    'dirty.closeTitle': 'Unsaved changes',
    'dirty.closeBody': 'Closing the window drops these changes.',
    'language.switchTitle': 'Switch language',
    'language.switchBody': 'There are unsaved changes. Save them before switching?',
    'language.saveSwitch': 'Save and switch',
    'language.discardSwitch': 'Switch without saving',
    'mouse.group': 'Mouse',
    'mouse.many': 'This computer has more than one mouse. After saving, this one is used.',
    'mouse.one': 'After saving, this mouse is used.',
    'mouse.use': 'Use this one',
    'mouse.none': 'No mouse found',
    'trigger.group': 'Stroke',
    'trigger.description': 'Hold this button while drawing. Button chords and the wheel use whichever button you press first.',
    'trigger.label': 'Trigger button',
    'display.group': 'Display',
    'display.description': 'The on-screen trail and the name after a shortcut. The next stroke picks this up after you save.',
    'display.namePlace': 'Name position',
    'display.bottom': 'Centered near the bottom',
    'display.pointer': 'Where the button was released',
    'display.width': 'Line width',
    'display.pixels': 'pixels',
    'recognize.group': 'Recognition',
    'recognize.description': 'These are the mouse’s own movement units, not screen pixels. The next stroke picks this up after you save.',
    'recognize.click': 'Still a click',
    'recognize.clickHint': 'Movement within this distance stays a normal click',
    'recognize.length': 'Shortest stroke',
    'recognize.lengthHint': 'Shorter than this does not count as a stroke',
    'recognize.duration': 'Longest hold',
    'recognize.durationHint': 'Milliseconds. Longer than this cancels the stroke',
    'recognize.maxRules': 'Rule limit',
    'recognize.rulesUnit': 'rules',
    'rules.group': 'Rules',
    'rules.addTooltip': 'Add a rule',
    'rules.emptyHint': 'Click Add on the right. A rule is one mouse action plus a shortcut.',
    'rules.count': 'Click a row to edit it. {count} of {max}.',
    'rules.emptyTitle': 'No rules yet',
    'rules.emptySubtitle': 'Add one, choose a stroke, two buttons, or hold-and-scroll, then record a shortcut.',
    'rules.deleteTooltip': 'Delete this rule',
    'rules.max': 'At most {max} rules',
    'rules.deleteTitle': 'Delete “{name}”?',
    'rules.deleteBody': 'The rule leaves the list. It is written to the file when you save.',
    'save.failed': 'Not saved',
    'save.mouse': 'Saved. This mouse is now in use',
    'save.reloaded': 'Saved. The running Strokelet reloaded the rules',
    'save.later': 'Saved. The next start will use these rules',
    'shape.wheel': 'Hold {hold}, scroll {direction}',
    'shape.chord': 'Hold {hold}, then press {press}',
    'shape.drawn': 'Stroke drawn while holding {trigger}',
    'shape.direction': 'Hold {trigger}, {direction}',
    'shape.unset': 'No action yet',
    'kind.wheel': 'Wheel',
    'kind.chord': 'Chord',
    'kind.stroke': 'Stroke',
    'direction.up': 'up',
    'direction.down': 'down',
    'direction.left': 'left',
    'direction.right': 'right',
    'button.left': 'Left',
    'button.right': 'Right',
    'button.middle': 'Middle',
    'button.forward': 'Forward side',
    'button.back': 'Back side',
    'rule.untitled': 'Incomplete',
    'rule.noShortcut': 'Not set',
    'editor.new': 'New rule',
    'editor.edit': 'Edit rule',
    'editor.how': 'How it starts',
    'editor.howDescription': 'Pick one. A stroke uses the trigger button in this window. Chords and the wheel start from the button you press first.',
    'editor.draw': 'Draw a stroke',
    'editor.drawEmpty': 'Hold {trigger}, draw, then release',
    'editor.chord': 'Mouse chord',
    'editor.chordEmpty': 'Hold one button, then press another',
    'editor.wheel': 'Hold and scroll',
    'editor.wheelEmpty': 'Hold a button, then roll the wheel once',
    'editor.preview': 'Stroke preview',
    'editor.previewReady': 'The small dot is the start. The large dot is where you let go.',
    'editor.previewEmpty': 'After you draw, the stroke shows up here.',
    'editor.then': 'Then what',
    'editor.thenDescription': 'While a shortcut is recorded, the keyboard is grabbed so the system does not handle it first.',
    'editor.shortcut': 'Shortcut',
    'editor.shortcutEmpty': 'Not recorded',
    'editor.screenName': 'Show on screen',
    'editor.nameGroup': 'On-screen name',
    'editor.nameDescription': 'Leave empty to show nothing. After a match it stays up for about a second. Position is chosen under Display.',
    'editor.cancelled': 'Cancelled',
    'editor.noBinary': 'strokelet was not found',
    'editor.drawPrompt': 'Hold {trigger}, draw a stroke, then release.',
    'editor.drawSaved': 'Stroke recorded. It is stored when you click Done.',
    'editor.notSaved': 'Nothing was saved',
    'editor.chordPrompt': 'Hold the first button, then press another. Left, right, middle, or a side button.',
    'editor.chordSaved': 'Chord recorded. It is stored when you click Done.',
    'editor.wheelPrompt': 'Hold a mouse button, then roll the wheel. Up, down, left, or right.',
    'editor.wheelSaved': 'Wheel action recorded. It is stored when you click Done.',
    'editor.shortcutPrompt': 'The keyboard is grabbed. Press the shortcut, then release the main key.',
    'editor.listening': 'Listening: {label}',
    'editor.listeningPlain': 'Listening…',
    'editor.shortcutSaved': 'Shortcut recorded. It is stored when you click Done.',
    'editor.needStroke': 'Draw a stroke first, or pick another action.',
    'editor.needChord': 'Press two mouse buttons first, or pick another action.',
    'editor.needWheel': 'Hold a button and roll the wheel, or pick another action.',
    'editor.needShortcut': 'Record a shortcut too.',
    'editor.nameTooLong': 'The on-screen name can be at most 16 characters.',
    'editor.noCheck': 'strokelet was not found, so the rules could not be checked',
    'editor.invalid': 'The rule is not valid',
    'editor.noResult': 'Recording returned nothing',
    'editor.interrupted': 'Recording was interrupted',
    'editor.previewPlaceholder': 'The stroke shows up here after you draw',
    'menu.disconnected': 'Not connected',
    'menu.connected': 'Connected',
    'menu.settings': 'Settings',
    'menu.pause': 'Pause',
    'menu.resume': 'Resume',
    'menu.quit': 'Quit',
    'error.clickRange': '“Still a click” must be between 1 and 400',
    'error.lengthRange': 'The shortest stroke must be longer than a click, and between 20 and 5000',
    'error.durationRange': 'The longest hold must be between 200 and 60000 milliseconds',
    'error.ruleCount': 'The rule limit must be between 1 and 64',
    'error.tooManyRules': 'At most {max} rules',
    'error.wheelAndButton': 'A rule cannot be both a mouse chord and a wheel action',
    'error.strokeAndButton': 'A rule cannot be both a stroke and a mouse chord',
    'error.duplicateWheel': 'That wheel action already has a rule',
    'error.sameButton': 'The two buttons in a chord must be different',
    'error.duplicateChord': 'That mouse chord already has a rule',
    'error.similarStroke': 'That stroke is too similar to one you already have',
    'error.nameNewline': 'The on-screen name cannot contain a line break',
    'error.nameLength': 'The on-screen name can be at most 16 characters',
    'error.bothShapes': 'A stroke cannot have both a direction and points',
    'error.shortStroke': 'A stroke needs at least two points',
    'error.longStroke': 'That stroke has too many points',
    'error.pointRange': 'A stroke point is out of range',
    'error.mixedShortcut': 'A shortcut cannot use both names and key codes',
    'error.emptyKey': 'The shortcut key is empty',
    'daemon.noKeyboard': 'No keyboard found',
    'daemon.timeout': 'Timed out. Nothing was saved',
    'daemon.draw': 'Hold {button}, draw on the screen, then release.',
    'daemon.wheelHint': 'Hold a mouse button, then roll the wheel.',
    'daemon.chordHint': 'Hold the first button, then press another. Left, right, middle, or a side button.',
    'daemon.grabbedDraw': 'The mouse is grabbed. Hold {button}, draw, then release.',
    'daemon.grabbedWheel': 'The mouse is grabbed. Hold a button, then roll the wheel.',
    'daemon.noWheel': 'The wheel did not move',
    'daemon.badHold': 'That button cannot start a stroke',
    'daemon.grabbedChord': 'The mouse is grabbed. Hold the first button, then press another.',
    'daemon.noSecond': 'No second mouse button was pressed',
    'daemon.badChord': 'That button cannot be part of a chord',
    'daemon.mouseBusy': 'The mouse is busy. Pause Strokelet from the panel first.',
    'daemon.tooLong': 'Held too long. Nothing was saved',
    'daemon.tooShort': 'That stroke was too short',
    'daemon.another': 'Another recording started',
    'daemon.released': 'Strokelet released the mouse. Nothing was saved',
    'daemon.notSaved': 'Nothing was saved',
    'daemon.tooManyModifiers': 'At most four modifier keys',
    'daemon.badKey': 'That key cannot be bound',
    'daemon.cancelled': 'Cancelled',
    'daemon.twoKeys': 'Two main keys were pressed. Record it again',
    'daemon.drawTimeout': 'No stroke within 8 seconds',
    'daemon.wheelTimeout': 'The wheel did not move within 8 seconds',
    'daemon.chordTimeout': 'No second mouse button within 8 seconds',
};

const DAEMON = [
    ['仍算点击的距离要在 1 到 400 之间', 'error.clickRange'],
    ['最短轨迹要大于仍算点击的距离，并且在 20 到 5000 之间', 'error.lengthRange'],
    ['最长按住要在 200 到 60000 毫秒之间', 'error.durationRange'],
    ['规则条数要在 1 到 64 之间', 'error.ruleCount'],
    ['这条规则不能同时有鼠标组合和滚轮', 'error.wheelAndButton'],
    ['这条规则不能同时有轨迹和鼠标组合', 'error.strokeAndButton'],
    ['这个滚轮动作已经有一条规则', 'error.duplicateWheel'],
    ['组合的两个键不能相同', 'error.sameButton'],
    ['这个鼠标组合已经有一条规则', 'error.duplicateChord'],
    ['这条轨迹和已有的太像', 'error.similarStroke'],
    ['屏幕名称不能换行', 'error.nameNewline'],
    ['屏幕名称最多 16 个字', 'error.nameLength'],
    ['stroke uses both a direction and points', 'error.bothShapes'],
    ['stroke needs at least two points', 'error.shortStroke'],
    ['stroke has too many points', 'error.longStroke'],
    ['stroke point is out of range', 'error.pointRange'],
    ['shortcut uses both names and key codes', 'error.mixedShortcut'],
    ['shortcut key is empty', 'error.emptyKey'],
    ['没有找到键盘', 'daemon.noKeyboard'],
    ['时间到了，这次没有保存', 'daemon.timeout'],
    ['先按住一个鼠标键，再滚一下滚轮。', 'daemon.wheelHint'],
    ['先按住起始键，再按另一个。左键、右键、中键或侧键都可以。', 'daemon.chordHint'],
    ['没有滚到滚轮', 'daemon.noWheel'],
    ['这个键不能当作起始键', 'daemon.badHold'],
    ['鼠标已暂时独占。先按住一个鼠标键，再滚一下滚轮。', 'daemon.grabbedWheel'],
    ['鼠标已暂时独占。先按住起始键，再按另一个。', 'daemon.grabbedChord'],
    ['没有按到另一个鼠标键', 'daemon.noSecond'],
    ['这个键不能当作组合', 'daemon.badChord'],
    ['鼠标被占用。请先在面板上暂停 Strokelet。', 'daemon.mouseBusy'],
    ['时间太长，这次没有保存', 'daemon.tooLong'],
    ['轨迹太短', 'daemon.tooShort'],
    ['已开始另一次录制', 'daemon.another'],
    ['演示放开了鼠标，这次没有保存', 'daemon.released'],
    ['这次没有保存', 'daemon.notSaved'],
    ['修饰键最多 4 个', 'daemon.tooManyModifiers'],
    ['这个键不能绑定', 'daemon.badKey'],
    ['已取消', 'daemon.cancelled'],
    ['按下了两个主键，请再录一次', 'daemon.twoKeys'],
    ['8 秒内没有画完一笔', 'daemon.drawTimeout'],
    ['8 秒内没有滚到滚轮', 'daemon.wheelTimeout'],
    ['8 秒内没有按到另一个鼠标键', 'daemon.chordTimeout'],
];

const BUTTON_WORDS = [
    ['侧键前进', 'forward'],
    ['侧键后退', 'back'],
    ['左键', 'left'],
    ['右键', 'right'],
    ['中键', 'middle'],
];

const BUTTON_TEMPLATES = [
    ['按住{button}，在屏幕上画一笔，然后松开。', 'daemon.draw'],
    ['鼠标已暂时独占。按住{button}，画一笔后松开。', 'daemon.grabbedDraw'],
];

export function translate(language, key, vars = {}) {
    const table = language === 'en' ? EN : ZH;
    let text = table[key] ?? ZH[key] ?? key;
    for (const [name, value] of Object.entries(vars))
        text = text.replaceAll(`{${name}}`, `${value}`);
    return text;
}

export function translateDaemon(language, message) {
    const text = `${message || ''}`.trim();
    const tooMany = text.match(/^最多 (\d+) 条规则$/);
    if (tooMany)
        return translate(language, 'error.tooManyRules', {max: tooMany[1]});
    for (const [template, key] of BUTTON_TEMPLATES) {
        for (const [word, button] of BUTTON_WORDS) {
            if (text === template.replace('{button}', word))
                return translate(language, key, {button: translate(language, `button.${button}`)});
        }
    }
    const known = DAEMON.find(([raw]) => text === raw);
    return known ? translate(language, known[1]) : text;
}

export function readLanguage() {
    try {
        const [ok, bytes] = GLib.file_get_contents(appearancePath());
        if (!ok)
            return 'zh';
        const data = JSON.parse(new TextDecoder().decode(bytes));
        return data.language === 'en' ? 'en' : 'zh';
    } catch {
        return 'zh';
    }
}

export function writeLanguage(language) {
    const path = appearancePath();
    let data = {};
    try {
        const [ok, bytes] = GLib.file_get_contents(path);
        if (ok)
            data = JSON.parse(new TextDecoder().decode(bytes));
    } catch {
        data = {};
    }
    data.language = language === 'en' ? 'en' : 'zh';
    const dir = GLib.path_get_dirname(path);
    GLib.mkdir_with_parents(dir, 0o755);
    GLib.file_set_contents(path, `${JSON.stringify(data, null, 2)}\n`);
}

function appearancePath() {
    return GLib.build_filenamev([GLib.get_user_config_dir(), 'strokelet', 'appearance.json']);
}
